name: Benchmark

on:
   push:
     branches: main
     paths: ['src/**', 'benches/**']

env:
   MOLD_VERSION: 2.4.0

jobs:
    benchmark_with_bencher:
      name: Continuous Benchmarking with Bencher
      runs-on: ubuntu-latest
      timeout-minutes: ${{ (github.ref == 'refs/heads/express' && 1) || 60 }}
      # This will fail whenever Bencher Cloud is down
      # or there are any breaking changes to the report format
      continue-on-error: true
      env:
        BENCHER_PROJECT: rust-template
        BENCHER_TESTBED: ubuntu-latest
        BENCHER_ADAPTER: rust
        BENCHER_API_TOKEN: ${{ secrets.BENCHER_API_TOKEN }}
      steps:
        - uses: actions/checkout@v4
        - uses: bencherdev/bencher@main
        - name: Dogfooding Benchmarks with Bencher
          run: |
            bencher run \
            --if-branch "$GITHUB_REF_NAME" \
            --else-if-branch "$GITHUB_BASE_REF" \
            --err \
            --github-actions ${{ secrets.GITHUB_TOKEN }} \
            "cargo bench"